<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bikes [
<!ELEMENT bikes    (bikename, model, modelspecs, numberofgears, biketype, bikespecs, color, specialfeatures, constructionmaterial, retailinfo, bikeprice, availableforpurchaseat, rideable)>
  <!ELEMENT bikename      (#PCDATA)>
  <!ELEMENT model    (#PCDATA)>
  <!ELEMENT modelspecs (#PCDATA)>
  <!ELEMENT numberofgears    (#PCDATA)>
  <!ELEMENT biketype      (#PCDATA)>
  <!ELEMENT bikespecs    (#PCDATA)>
  <!ELEMENT color (#PCDATA)>
  <!ELEMENT specialfeatures    (#PCDATA)>
  <!ELEMENT constructionmaterial      (#PCDATA)>
  <!ELEMENT retailinfo    (#PCDATA)>
  <!ELEMENT bikeprice (#PCDATA)>
  <!ELEMENT availableforpurchaseat    (#PCDATA)>
  <!ELEMENT rideable    (#PCDATA)>
]>
<bikes>
<bikename>GT</bikename>
<model>Fury Elite</model>
<modelspecs>
<numberofgears>9</numberofgears>
<biketype>Mountain</biketype>
</modelspecs>
<bikespecs>
<color>White</color>
<specialfeatures>discbrakes</specialfeatures>
<constructionmaterial>Aluminum Alloy</constructionmaterial>
</bikespecs>
<retailinfo>
<bikeprice>$3360</bikeprice>
<availableforpurchaseat>online</availableforpurchaseat>
</retailinfo>
<rideable>yes</rideable>
</bikes>